[default]
ELASTIC_APM_SERVER_URL=""
ELASTIC_APM_SECRET_TOKEN=""
ELASTIC_APM_ENVIRONMENT="homolog"
ELASTIC_APM_CAPTURE_BODY="all"
ELASTIC_APM_CAPTURE_HEADERS="true"
REDIS_DB=""
REDIS_HOST=""
REDIS_PORT=""
REDIS_URL=""
EXPIRATION_HOURS = 1
[default.database]
    driver="postgresql+psycopg2"
    name="vpo"
    host="localhost"
    port=5432
    user="vpo"
    password="vpo"
    metadata = { schema="vpo" }

[development]
[development.database]
    driver="postgresql+psycopg2"
    name="vpo"
    host="localhost"
    port=5432
    user="vpo"
    password="vpo"
    metadata = { schema="vpo" }

[homologation]
[homologation.database]
    driver="postgresql+psycopg2"
    name="vpo-fms-database-homolog"
    host="10.142.0.9"
    port=5432
    user="vpo-fms-database-homolog"
    password="RE41akg5QnlDdjNhdk95UVF1YU12VFlRMFZzd3h3"
    metadata = { schema="vpo" }
