default_language_version:
  python: python3.12


repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
      - id: name-tests-test
        args: [--pytest-test-first]
        exclude: 'tests/tools/.*|tests/mocks/.*'
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key