# Este workflow instala dependências usando Poetry, roda pre-commit e testes com pytest

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do repositório
    - uses: actions/checkout@v4

      # Configura o Python na versão 3.12
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

      # Instala o Poetry
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

      # Instala as dependências do projeto e do desenvolvimento com Poetry
    - name: Install dependencies with Poetry
      run: |
        poetry install

      # Instala o pre-commit e executa os hooks em todos os arquivos
    - name: Run pre-commit hooks
      run: |
        poetry run pre-commit install
        poetry run pre-commit run --all-files

      # Executa os testes com pytest
    - name: Test with pytest
      run: |
        poetry run pytest
